"""
A command-line tool for step-by-step debugging of the COMPARISON alert logic.

This script isolates the analysis of a single time window, allowing developers to
see exactly why an alert was or was not generated by the ComparisonConfirmation logic.

Usage:
    python3 tests/debug/alert/approach/comparison/debug_executor.py \\
        --symbol [MAIN_SYMBOL_TICKER] \\
        --start-time [YYYY-MM-DD HH:MM:SS] \\
        --end-time [YYYY-MM-DD HH:MM:SS]

Example:
    python3 tests/debug/alert/approach/comparison/debug_executor.py \\
        --symbol "41I1FB000" \\
        --start-time "2025-10-20 09:00:00" \\
        --end-time "2025-10-20 10:00:00"
"""
import sys
import os
import argparse
import pandas as pd
import logging
import importlib
from typing import Optional

# This is the standard and robust way to ensure the script can find the 'src' module.
# It adds the project's root directory to the Python path.
project_root = os.path.abspath(os.path.join(os.path.dirname(__file__), '../../../../../'))
if project_root not in sys.path:
    sys.path.insert(0, project_root)

# --- End Debugging ---

from src.stockreports.config import loader
from src.stockreports.utils.data_utils import load_live_data
from src.stockreports.alert.approach.COMPARISON.executor import ComparisonExecutor
from src.stockreports.alert.approach.COMPARISON.settings import ComparisonSignalSettings
import src.stockreports.alert.approach.COMPARISON.settings as signal_settings_module

# Setup basic logging for the debug script
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')


def run_debug_analysis(symbol, start_time_str, end_time_str):
    """
    Sets up the environment and runs the debug analysis by calling the main COMPARISON executor
    with a DataFrame representing the specified time window, in DEPLOYMENT mode.
    """
    print(f"--- Starting Debug Analysis for COMPARISON on {symbol} from {start_time_str} to {end_time_str} (DEPLOYMENT MODE) ---")

    # --- 1. Load Configuration & Set Mode ---
    importlib.reload(signal_settings_module)
    importlib.reload(loader)
    settings = loader.get_settings()
    settings.MODE = 'DEPLOYMENT' # Set to DEPLOYMENT mode
    
    approach_settings = ComparisonSignalSettings(symbol)
    ref_symbol = approach_settings.referenced_symbol
    if not ref_symbol:
        print(f"ERROR: No referenced_symbol found for '{symbol}' in signal settings.")
        return

    print("\n--- Settings ---")
    print(f"Mode: {settings.MODE}")
    print(f"Symbol: {symbol}")
    print(f"Referenced Symbol: {ref_symbol}")
    print(f"Lookback Window: {approach_settings.lookback_window}")
    print(f"MA Period: {approach_settings.ma_short_period}")

    # --- 2. Prepare the specific DataFrame for analysis ---
    timezone = settings.TRADING_HOURS[settings.MARKET_COUNTRY_CODE]['timezone']
    start_time = pd.to_datetime(start_time_str).tz_localize(timezone)
    end_time = pd.to_datetime(end_time_str).tz_localize(timezone)

    print(f"\n--- Fetching data for main symbol from {start_time} to {end_time} (Timezone: {timezone}) ---")
    try:
        # Convert datetime objects to integer UTC timestamps for the API call
        from_timestamp = int(start_time.timestamp())
        to_timestamp = int(end_time.timestamp())

        # Fetch data only for the main symbol. The main executor is responsible for fetching its own dependencies.
        df_for_analysis = load_live_data(symbol, from_timestamp=from_timestamp, to_timestamp=to_timestamp)

        if df_for_analysis is None or df_for_analysis.empty:
            print(f"ERROR: Could not retrieve data for the main symbol '{symbol}' in the range {start_time} to {end_time}.")
            return
        
        print("Data successfully fetched for the required window.")

    except Exception as e:
        print(f"ERROR: An error occurred during data fetching. {e}")
        return

    # The executor expects lowercase columns and a 'symbol' column
    df_for_analysis.columns = [col.lower() for col in df_for_analysis.columns]
    df_for_analysis['symbol'] = symbol
    
    # In DEPLOYMENT mode, new_candle_count determines how far back the executor looks.
    # We set it to the size of our target window.
    new_candle_count = len(df_for_analysis)

    # --- 3. Call the main executor ---
    print(f"\n--- Calling main executor with a dataframe of {len(df_for_analysis)} candles ---")
    executor = ComparisonExecutor(symbol=symbol)
    alert_result = executor.run(df=df_for_analysis.reset_index(), new_candle_count=new_candle_count)

        # --- 4. Report results ---
    print("\n\n===== OVERALL RESULT =====")
    if alert_result.status == "FAILED":
        print(f"EXECUTOR FAILED: {alert_result.message}")
    elif not alert_result.alerts.empty:
        print("✅✅✅ ALERT(S) FOUND! ✅✅✅")
        
        # Create a copy to avoid SettingWithCopyWarning
        alerts_df = alert_result.alerts.copy()

        # Convert alert_time column to datetime objects and make it timezone-aware
        alerts_df['alert_time'] = pd.to_datetime(alerts_df['alert_time']).dt.tz_convert(timezone)

        # Filter alerts to only show those within our precise start/end time window
        alerts_in_range = alerts_df[
            (alerts_df['alert_time'] >= start_time) & 
            (alerts_df['alert_time'] <= end_time)
        ]
        if not alerts_in_range.empty:
            print(alerts_in_range.to_string())
        else:
            print("Alerts were found by the executor, but they were outside the specified time range.")
    else:
        print("No alerts were generated by the executor in the provided data.")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Debug the COMPARISON alert logic by calling the main executor with a specific time window.")
    parser.add_argument("--symbol", required=True, help="The primary symbol to analyze (e.g., '41I1FB000'). The reference symbol will be loaded from settings.")
    parser.add_argument("--start-time", required=True, help="The start of the time range to analyze (e.g., '2025-11-19 10:32:00').")
    parser.add_argument("--end-time", required=True, help="The end of the time range to analyze (e.g., '2025-11-19 10:40:00').")
    
    args = parser.parse_args()
    
    run_debug_analysis(args.symbol, args.start_time, args.end_time)
