import json
import os
import pandas as pd
import glob
import logging
import pytz
from tabulate import tabulate
import sys
from datetime import datetime, timedelta
import importlib
from typing import Optional, cast
import time

# --- Path Setup ---
# This is handled by the entry-point script, but kept for robustness
project_root = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..', '..'))
if project_root not in sys.path:
    sys.path.insert(0, project_root)

# --- Settings Loader ---
# This MUST be the first project import to ensure settings are fresh.
from src.stockreports.config import loader
from src.stockreports.notification.close_position_scheduler import check_and_notify
from src.stockreports.alert.model.models import AlertNotification

# Other modules should use the getters to access the loaded modules.
settings = loader.get_settings()
signal_settings = loader.get_signal_settings()
notification_settings = loader.get_notification_settings()
validation_settings = loader.get_validation_settings()

# --- Project Imports ---
from src.stockreports.notification.notification_manager import NotificationManager
from src.stockreports.utils.data_utils import (
    fetch_intraday_data, 
    load_data_for_development, load_live_data
)
from src.stockreports.utils.time_utils import is_trading_hours, SESSIONS, TimeSimulator, TIMEZONE
from src.stockreports.utils.historical_data_manager import update_historical_data
from src.stockreports.alert.model.models import AlertNotification, AlertResult, AlertData, AlertSummary
from src.stockreports.alert.common.validation.validation import calculate_alert_performance
from src.stockreports.alert.common.validation.price_adjustment import adjust_prices_by_symbol
from src.stockreports.alert.common.profitability_simulator import simulate_profitability
from src.stockreports.utils.report_utils import save_profitability_report, save_alert_report, update_alert_summary
from src.stockreports.utils.alert_utils import calculate_suggested_prices
from src.stockreports.alert.price_movement_alerter import PriceMovementAlerter

# --- Constants & Configuration ---
DEFAULT_APPROACH = "VRA"


def ensure_alert_result(result: object) -> AlertResult:
    """
    Type guard function to ensure executor.run() returns AlertResult.
    
    Validates at runtime that the returned object is an AlertResult instance,
    providing explicit type safety for further processing.
    
    Args:
        result (object): The return value from executor.run()
        
    Returns:
        AlertResult: The validated AlertResult instance
        
    Raises:
        TypeError: If the result is not an AlertResult instance
        
    Example:
        result: AlertResult = ensure_alert_result(executor.run(df=daily_df, new_candle_count=10))
        if result.has_alerts:
            for _, alert_row in result.alerts.iterrows():
                # Process alert_row
    """
    if not isinstance(result, AlertResult):
        raise TypeError(
            f"executor.run() must return AlertResult, got {type(result).__name__}. "
            f"Value: {result}"
        )
    return cast(AlertResult, result)


class SymbolAlerter:
    """
    Manages the entire alerting lifecycle for a single stock symbol.
    """
    def __init__(self, symbol: str):
        """
        Initializes the alerter for a specific symbol.
        """
        self.symbol = symbol
        self.notification_manager = NotificationManager()
        self._setup_logging()

    def _setup_logging(self):
        """Configures logging to file and console."""
        log_dir = os.path.join(project_root, "logs", settings.MODE.lower())
        os.makedirs(log_dir, exist_ok=True)
        log_file_path = os.path.join(log_dir, f"alerter_{self.symbol}.log")

        # Use a logger specific to this symbol instance
        self.logger = logging.getLogger(f"SymbolAlerter.{self.symbol}")
        # Avoid adding handlers if they already exist
        if not self.logger.handlers:
            # File handler
            file_handler = logging.FileHandler(log_file_path)
            file_handler.setFormatter(logging.Formatter("%(asctime)s - %(levelname)s - %(message)s"))
            self.logger.addHandler(file_handler)

            # Console handler
            stream_handler = logging.StreamHandler(sys.stdout)
            stream_handler.setFormatter(logging.Formatter("%(asctime)s - %(levelname)s - %(message)s"))
            self.logger.addHandler(stream_handler)
        
        self.logger.info(f"Logging configured for {self.symbol}. Log file: {log_file_path}")

    def _send_scheduled_notification(self, notification: Optional[AlertNotification]):
        """
        Sends a notification that was generated by the scheduler.
        """
        if notification:
            self.logger.info(f"Scheduler: Sending scheduled notification: {notification.signal}")
            self.notification_manager._send_alert(notification)
        else:
            self.logger.debug("Scheduler: No scheduled notifications to send at this time.")

    def _get_approach_executor(self, approach_name: str):
        try:
            module_path = f"src.stockreports.alert.approach.{approach_name.upper()}.executor"
            executor_module = importlib.import_module(module_path)
            # Convert approach_name (e.g., 'CONSECUTIVE_POWER_CANDLES') to a class name (e.g., 'ConsecutivePowerCandlesExecutor')
            class_name_parts = [part.capitalize() for part in approach_name.split('_')]
            executor_class_name = "".join(class_name_parts) + "Executor"
            executor_class = getattr(executor_module, executor_class_name)
            # Instantiate the executor with the symbol
            return executor_class(self.symbol)
        except (ImportError, AttributeError) as e:
            self.logger.error(f"Could not load approach '{approach_name}'. Error: {e}")
            return None

    def _get_approaches_for_symbol(self) -> list:
        """
        Gets the list of approaches to run for this symbol.
        
        Priority order:
        1. Symbol-specific approaches from SYMBOL_ALERT_APPROACHES
        2. Default approaches from ALERT_APPROACHES_DEFAULT
        3. Legacy approaches from ALERT_APPROACHES (backward compatibility)
        4. Hard fallback: [DEFAULT_APPROACH]
        
        This allows different symbols to have different alert strategies,
        with sensible fallbacks for backward compatibility.
        
        Returns:
            list: List of approach names to run for this symbol
        """
        # Priority 1: Symbol-specific configuration
        symbol_config = getattr(settings, 'SYMBOL_ALERT_APPROACHES', {})
        if isinstance(symbol_config, dict) and self.symbol in symbol_config:
            approaches = symbol_config[self.symbol]
            self.logger.info(f"Symbol-specific approaches for '{self.symbol}': {approaches}")
            return approaches
        
        # Priority 2: Default approaches for undefined symbols
        default_approaches = getattr(settings, 'ALERT_APPROACHES_DEFAULT', None)
        if default_approaches:
            self.logger.info(f"Using default approaches for '{self.symbol}': {default_approaches}")
            return default_approaches
        
        # Priority 3: Legacy global approaches (backward compatibility)
        legacy_approaches = getattr(settings, 'ALERT_APPROACHES', None)
        if legacy_approaches:
            self.logger.info(f"Using legacy ALERT_APPROACHES for '{self.symbol}': {legacy_approaches}")
            return legacy_approaches
        
        # Priority 4: Hard fallback
        fallback = [DEFAULT_APPROACH]
        self.logger.warning(f"No approaches configured for symbol '{self.symbol}'. Using fallback: {fallback}")
        return fallback

    def execute(self):
        self.logger.info(f"Executing alerter for symbol: {self.symbol}...")
        if settings.MODE == "DEVELOPMENT":
            self._run_development_mode()
        elif settings.MODE == "DEPLOYMENT":
            self._run_deployment_mode()
        self.logger.critical(f"Execution finished for symbol: {self.symbol}.")

    def _enrich_and_save_reports(self, result: AlertResult, processing_date: str):
        """
        Enriches the alert result with suggested prices and saves all relevant reports.
        """
        # This function now only saves the report, enrichment is done prior.
        save_alert_report(result, self.symbol, processing_date)
        if settings.MODE == "DEVELOPMENT":
            update_alert_summary(result, self.symbol, processing_date)

    def _run_development_mode(self):
        self.logger.info(f"Running in DEVELOPMENT mode for {self.symbol}.")
        master_df = load_data_for_development(self.symbol)
        if master_df.empty:
            self.logger.error(f"No data loaded for {self.symbol} in development mode, cannot proceed.")
            return
        
        dates_to_process = sorted(master_df['time'].dt.strftime('%Y-%m-%d').unique())
        
        for processing_date in dates_to_process:
            self._process_date(master_df, processing_date)

    def _run_deployment_mode(self):
        """
        Acts as a resilient supervisor for the monitoring session.
        If the session crashes, this function logs the error and restarts it.
        If the session completes cleanly (replay or live), it exits.
        """
        self.logger.info(f"Entering resilient deployment mode for {self.symbol}.")
        while True:
            try:
                # This function returns True when the monitoring loop finishes without error.
                session_completed_cleanly = self._perform_monitoring_session()

                # If the session finished its work, break the supervisor loop.
                if session_completed_cleanly:
                    self.logger.info(f"Monitoring session for {self.symbol} completed successfully. Exiting supervisor.")
                    break

            except KeyboardInterrupt:
                self.logger.info(f"Stopping real-time monitor for {self.symbol}.")
                break  # Exit the supervisor loop.
            except Exception as e:
                self.logger.critical(
                    f"The monitoring session for {self.symbol} crashed. Restarting... Error: {e}",
                    exc_info=True
                )
                # In live mode, wait before restarting. In replay, stop immediately on error.
                if settings.DEBUG_REPLAY_START_TIME is None:
                    self.logger.info(f"Waiting for {settings.MONITORING_INTERVAL_SECONDS} seconds before restarting...")
                    time.sleep(settings.MONITORING_INTERVAL_SECONDS)
                else:
                    self.logger.error("Exiting replay due to critical error.")
                    break

    def _perform_monitoring_session(self) -> bool:
        """
        Executes a single, continuous monitoring session for the symbol.
        This function runs until the time simulator indicates it should stop.

        Returns:
            bool: True if the session completed without error, signaling a clean exit.
        """
        time_simulator = TimeSimulator(
            replay_start_str=settings.DEBUG_REPLAY_START_TIME,
            interval_seconds=settings.MONITORING_INTERVAL_SECONDS
        )
        
        self.logger.info(f"Starting new monitoring session for {self.symbol} on {time_simulator.processing_date}")
        
        master_df = pd.DataFrame()
        triggered_levels_today = set()

        # This is the main operational loop for fetching and analyzing data.
        # Main monitoring loop
        while time_simulator.is_running():
            current_time = time_simulator.get_current_time()
            
            # --- Check for scheduled 'Close Position' notifications ---
            self.logger.debug("Scheduler: Triggering check for scheduled notifications.")
            scheduled_notification = check_and_notify(current_time)
            self._send_scheduled_notification(scheduled_notification)

            # Check if within trading hours before fetching data and processing
            if not is_trading_hours(current_time):
                self.logger.info(f"Outside trading hours ({current_time.strftime('%H:%M:%S')}). Waiting for next interval.")
                if time_simulator.is_replay_mode():
                    time_simulator.advance() # Move time forward to find the next trading window
                    continue
                else:
                    time.sleep(900) # In live mode, wait 15 minutes
                    continue
            
            self.logger.info(f"\n--- New Interval for {self.symbol}: Analyzing at {current_time.strftime('%Y-%m-%d %H:%M:%S')} ---")

            # Define the time window for the data fetch
            to_dt = current_time
            if master_df.empty:
                # First run: fetch all data from the start of the day
                all_starts = [times['start'] for times in SESSIONS.values()]
                start_time_str = min(all_starts)
                start_h, start_m = map(int, start_time_str.split(':'))
                from_dt = to_dt.replace(hour=start_h, minute=start_m, second=0, microsecond=0)
            else:
                # Subsequent runs: fetch data from the last known point in time
                last_known_time = master_df['time'].max()
                from_dt = last_known_time

            from_timestamp = int(from_dt.timestamp())
            to_timestamp = int(to_dt.timestamp())

            # Fetch the latest data slice
            latest_df = load_live_data(self.symbol, from_timestamp, to_timestamp)

            if latest_df.empty and not time_simulator.is_replay_mode():
                self.logger.warning("The latest DataFrame is still empty in live mode. Waiting for data.")
                time.sleep(settings.MONITORING_INTERVAL_SECONDS)
                continue
            
            new_candle_count = 0
            if not latest_df.empty:
                new_candle_count = len(latest_df)
                # Append new data and remove duplicates, keeping the last entry
                master_df = pd.concat([master_df, latest_df]).drop_duplicates(subset=['time'], keep='last').sort_values(by='time').reset_index(drop=True)
                
                # --- Update Central Cache ---
                # Save the updated master_df to the central historical data manager
                update_historical_data(self.symbol, master_df)

            if master_df.empty:
                self.logger.warning("Master DataFrame is empty. Advancing to next interval.")
                time_simulator.advance()
                continue

            # --- Price Movement Alerter ---
            price_alerter = PriceMovementAlerter(self.symbol, triggered_levels_today)
            price_alert_result: AlertResult = price_alerter.execute(master_df)
            
            if price_alert_result.has_alerts:
                self.logger.info(f"Found {len(price_alert_result.confirmed_alerts)} price movement alerts.")
                
                # Note: Price movement alerts typically don't have suggested entry points
                # These remain None, which is acceptable for informational price alerts
                for alert in price_alert_result.confirmed_alerts:
                    # Optional: Apply suggested prices if needed for consistency
                    # perf_price, struct_price = calculate_suggested_prices(
                    #     signal=alert.signal,
                    #     alert_time=alert.alert_time,
                    #     approach=alert.approach
                    # )
                    # alert.performance_suggested_price = perf_price
                    # alert.structural_suggested_price = struct_price
                    pass
                
                self.notification_manager.process_and_notify(price_alert_result, self.symbol)


            # --- Standard Approach Alerter ---
            # The logic for slicing the dataframe is now removed.
            # The full master_df is passed to the executors.
            if master_df.empty:
                self.logger.warning("Master DataFrame is empty, cannot run approaches. Waiting.")
                time_simulator.advance()
                if not time_simulator.is_replay_mode():
                    time.sleep(settings.MONITORING_INTERVAL_SECONDS)
                continue

            approaches_to_run = self._get_approaches_for_symbol()
            for approach_name in approaches_to_run:
                self.logger.info(f"--- Running Approach: {approach_name} for {self.symbol} ---")

                executor = self._get_approach_executor(approach_name)
                if not executor: continue
                
                # Pass the full master_df to the executor's run method.
                result: AlertResult = ensure_alert_result(
                    executor.run(df=master_df.copy(), new_candle_count=new_candle_count)
                )
                if result.has_alerts:
                    # Step 1: Enrich alerts with suggested prices
                    for alert in result.confirmed_alerts:  # Type: AlertData (inferred from List[AlertData])
                        perf_price, struct_price = calculate_suggested_prices(
                            signal=alert.signal,
                            alert_time=alert.alert_time,
                            approach=alert.approach
                        )
                        alert.performance_suggested_price = perf_price
                        alert.structural_suggested_price = struct_price

                    # Step 2: Send notification with enriched data
                    self.notification_manager.process_and_notify(result, self.symbol)
                    
                    # Step 3: Save the enriched report.
                    self._enrich_and_save_reports(result, time_simulator.processing_date)
            
            self.logger.info(f"Interval finished. Advancing time...")
            time_simulator.advance()
            # In live mode, we still need to wait for the actual interval time to pass.
            if not time_simulator.is_replay_mode():
                time.sleep(settings.MONITORING_INTERVAL_SECONDS)

        self.logger.info(f"Monitoring session for {self.symbol} has concluded.")
        # The session finished cleanly, return True to stop the supervisor loop.
        return True

    def _process_date(self, master_df, processing_date):
        self.logger.info(f"\n{'='*20} Processing Date: {processing_date} for {self.symbol} {'='*20}")
        start_date = pd.Timestamp(processing_date, tz=TIMEZONE).replace(hour=0, minute=0, second=0)
        end_date = start_date + timedelta(days=1)
        daily_df = master_df[(master_df['time'] >= start_date) & (master_df['time'] < end_date)].copy()

        if daily_df.empty:
            self.logger.warning(f"No data found for {self.symbol} on {processing_date}.")
            return

                        # Filter by trading hours
        if SESSIONS:
            combined_mask = pd.Series([False] * len(daily_df), index=daily_df.index)
            time_col = daily_df['time'].dt.time
            for session_name, hours in SESSIONS.items():
                start_time = datetime.strptime(hours['start'], '%H:%M').time()
                end_time = datetime.strptime(hours['end'], '%H:%M').time()
                session_mask = (time_col >= start_time) & (time_col <= end_time)
                combined_mask = combined_mask | session_mask
            daily_df = daily_df[combined_mask]

        if daily_df.empty:
            self.logger.warning(f"No data for {self.symbol} on {processing_date} after filtering by trading hours.")
            return
        
        self.logger.info(f"Loaded {len(daily_df)} data points for {self.symbol} on {processing_date}.")
        
        all_alerts_for_day = []
        approaches_to_run = self._get_approaches_for_symbol()
        
        for approach_name in approaches_to_run:
            self.logger.info(f"\n--- Running Approach: {approach_name} for {self.symbol} on {processing_date} ---")
            executor = self._get_approach_executor(approach_name)
            if not executor: continue
            
            # Pass the full length of the daily dataframe as new_candle_count in development mode
            result: AlertResult = ensure_alert_result(
                executor.run(df=daily_df.copy(), new_candle_count=len(daily_df))
            )
            
            if result.has_alerts:
                # Step 1: Enrich alerts with suggested prices
                for alert in result.confirmed_alerts:  # Type: AlertData (inferred from List[AlertData])
                    perf_price, struct_price = calculate_suggested_prices(
                        signal=alert.signal,
                        alert_time=alert.alert_time,
                        approach=alert.approach
                    )
                    alert.performance_suggested_price = perf_price
                    alert.structural_suggested_price = struct_price

                # Step 2: Send notifications (fire-and-forget)
                self.notification_manager.process_and_notify(result, self.symbol)

                # Step 3: Further enrich with validation data and save reports
                if settings.MODE == "DEVELOPMENT":
                    for alert in result.confirmed_alerts:  # Type: AlertData (inferred from List[AlertData])
                        alert.symbol = self.symbol
                        validated_alert = calculate_alert_performance(alert, daily_df, validation_settings.VALIDATION_PERIOD_MINUTES)
                        # Copy validated fields back to alert
                        alert.status = validated_alert.status
                        alert.profit_loss = validated_alert.profit_loss
                        alert.time_to_best_price = validated_alert.time_to_best_price
                        alert.min_expected_profit_loss = validated_alert.min_expected_profit_loss
                        alert.validation_price_time = validated_alert.validation_price_time
                
                self._enrich_and_save_reports(result, processing_date)
                
                # Collect alerts for end-of-day profitability simulation
                all_alerts_for_day.extend([a.to_dict() for a in result.confirmed_alerts])

        if settings.MODE == "DEVELOPMENT" and all_alerts_for_day:
            self.logger.info(f"\n--- Running Profitability Simulation for {self.symbol} on {processing_date} ---")
            simulation_summary = simulate_profitability(all_alerts_for_day, daily_df)
            
            # Log the summary in a readable format
            self.logger.info("Profitability Simulation Summary:")
            self.logger.info(f"  Total Trades: {simulation_summary.total_trades}")
            self.logger.info(f"  Successful Trades: {simulation_summary.successful_trades} ({simulation_summary.success_rate})")
            self.logger.info(f"  Failed Trades: {simulation_summary.failed_trades} ({simulation_summary.failure_rate})")
            self.logger.info(f"  Total Profit/Loss: {simulation_summary.total_profit_loss:.2f}")

            # Save the detailed report using the new utility function
            save_profitability_report(
                summary_data=simulation_summary,
                symbol=self.symbol,
                date_str=processing_date,
                logger_instance=self.logger
            )
