class Approach:
    RCM = "RCM"
    STRONG_CANDLE = "STRONG_CANDLE"
    CONSISTENT_MOMENTUM = "CONSISTENT_MOMENTUM"
    ICHIMOKU = "ICHIMOKU"
    SUPPORT_RESISTANCE_BREAK = "SUPPORT_RESISTANCE_BREAK"
    MOMENTUM_EXHAUSTION = "MOMENTUM_EXHAUSTION"
    CONSECUTIVE_POWER_CANDLES = "CONSECUTIVE_POWER_CANDLES"
    CONSOLIDATION_BREAKOUT = "CONSOLIDATION_BREAKOUT"
    COMPARISON = "COMPARISON"

class Mode:
    DEVELOPMENT = "DEVELOPMENT"
    DEPLOYMENT = "DEPLOYMENT"

class Signal:
    BUY = "BUY"
    SELL = "SELL"

class Trend:
    UPTREND = "uptrend"
    DOWNTREND = "downtrend"

class AlertKeys:
    TREND = "trend"
    SIGNAL = "signal"
