class Approach:
    RCM = "RCM"
    STRONG_CANDLE = "STRONG_CANDLE"
    CONSISTENT_MOMENTUM = "CONSISTENT_MOMENTUM"
    ICHIMOKU = "ICHIMOKU"
    SUPPORT_RESISTANCE_BREAK = "SUPPORT_RESISTANCE_BREAK"

class Mode:
    DEVELOPMENT = "DEVELOPMENT"
    DEPLOYMENT = "DEPLOYMENT"
